var color = 'red';
console.log(color);
console.log(typeof (color));
var num = 123;
console.log(num);
console.log(typeof (num));
var dec = 456.789;
console.log(dec);
console.log(typeof (dec));
var b = true;
console.log(b);
console.log(typeof (b));
b = false;
console.log(b);
console.log(typeof (b));
